server.port=8080

spring.datasource.url=${QUIZ_DB_URL}
spring.datasource.username=${QUIZ_DB_USER}
spring.datasource.password=${QUIZ_DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.thymeleaf.cache=false
