-- MySQL schema for the Real-Time Quiz Platform
CREATE DATABASE IF NOT EXISTS kahoot CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kahoot;

CREATE TABLE IF NOT EXISTS users (
  userID BINARY(16) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userID)
);

CREATE TABLE IF NOT EXISTS games (
  gameID INT AUTO_INCREMENT PRIMARY KEY,
  userID BINARY(16) NOT NULL,
  gameTitle VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lastPlayedAt TIMESTAMP NULL,
  FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions (
  questionID INT AUTO_INCREMENT PRIMARY KEY,
  gameID INT NOT NULL,
  questionPrompt TEXT NOT NULL,
  correctAnswer CHAR(1) NOT NULL,
  choiceA TEXT NOT NULL,
  choiceB TEXT NOT NULL,
  choiceC TEXT NOT NULL,
  choiceD TEXT NOT NULL,
  FOREIGN KEY (gameID) REFERENCES games(gameID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS game_sessions (
  sessionID INT AUTO_INCREMENT PRIMARY KEY,
  gameID INT NOT NULL,
  inviteCode VARCHAR(12) NOT NULL UNIQUE,
  status ENUM('LOBBY','ACTIVE','FINISHED') DEFAULT 'LOBBY',
  timePerQuestion INT DEFAULT 20,
  maxPlayers INT DEFAULT 50,
  startedAt TIMESTAMP NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (gameID) REFERENCES games(gameID)
);
